name: CI

on:
  push:
    # CI shouldn't need to run on the main branch,
    # just working & PR branches
    branches-ignore:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - name: "[Git] Checkout code"
        uses: actions/checkout@v2
      - name: "[Setup] Install test dependencies"
        run: |
          apt update
          apt install -y npm
          npm install -g s3rver
      - name: "[Setup] Install project dependencies"
        run: shards install
      - name: "[Test] Run Specs"
        env:
          CRYSTAL_ENV: test
        run: crystal spec --error-trace
